// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASr2eeue8be4mj_7XLMjxYNzcfxcbiHMA',
    appId: '1:86917190723:android:fae87b5581e81fd17a30f6',
    messagingSenderId: '86917190723',
    projectId: 'eventro-24121',
    storageBucket: 'eventro-24121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQ469o_DdvpCY48hZWC8knuBwoRgO0Jg',
    appId: '1:86917190723:ios:c7552ab68b8ca8287a30f6',
    messagingSenderId: '86917190723',
    projectId: 'eventro-24121',
    storageBucket: 'eventro-24121.appspot.com',
    androidClientId: '86917190723-6agsn92o4f7gvbg1qctogsemqbcd1sii.apps.googleusercontent.com',
    iosClientId: '86917190723-3gj9oujinvfunkelrbn7itsg9c87pq6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventro',
  );
}
